2018-07-09 11:21:37,096 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 192, in valves
    valves = Valve.query.order_by(Valve.id)
NameError: name 'Valve' is not defined
2018-07-09 11:25:08,395 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 11:25:10,182 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 194, in valves
    valves=valves.item)
AttributeError: 'BaseQuery' object has no attribute 'item'
2018-07-09 11:26:34,413 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 11:26:37,483 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 194, in valves
    valves=valves.item)
AttributeError: 'list' object has no attribute 'item'
2018-07-09 11:26:47,882 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 194, in valves
    valves=valves.item)
AttributeError: 'list' object has no attribute 'item'
2018-07-09 11:27:04,527 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 11:27:07,379 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 194, in valves
    valves=valves.item)
AttributeError: 'list' object has no attribute 'item'
2018-07-09 11:29:09,725 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 11:29:11,448 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 193, in valves
    return render_template('valves.html', title='Sprinkler Valves', form=form,
NameError: name 'form' is not defined
2018-07-09 11:29:51,058 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 11:29:52,719 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 195, in valves
    valves=valves.item)
AttributeError: 'list' object has no attribute 'item'
2018-07-09 11:33:03,695 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
